@startuml
actor Человек as H
actor Компьютер as R
actor Банкир as B


rectangle Monopoly {
usecase "Выдать деньги" as UC0
usecase "Сходить на n шагов" as UC1
usecase "Купить клетку" as UC2
usecase "Попасть в тюрьму" as UC3
usecase "Продать имущество" as UC4
usecase "Заплатить аренду" as UC5
usecase "Построить недвижимость" as UC6
usecase "Победа" as UC7
usecase "Банкротство" as UC8

}

B --> UC0
H --> UC1
H --> UC2
H --> UC6
R --> UC1
R --> UC5
R --> UC3
R --> UC8
H --> UC7
UC6 <|-- UC2 
UC4 <|-- UC2
UC4 <|-- UC6
@enduml